* Todo
** TODO make deactivation interface
How do I present the objects in list form to be read by completing-read? prin1-to-string? of what?
** DONE dispatch based on event
example usage:
(circe-actions-get 'message "irc.message" arg-list)

implemented instead with circe-actions-plistify
** TODO illustrate with doctor-callbacks
M-x doctor is weird. would be a humorous example, but the way it's designed is strange as all hell.
** TODO Tests!
Should be implemented with Buttercup, I think. Testing interactively with ERT is a pain, I've already had to build my own mock functions (that don't accurately reflect the actual environment). I'd much rather have the ability to call the real functions in a mock environment. ERT has no easy facility to do this.

Further, it would probably be a good idea to move some of the ert tests in circe-actions to buttercup as well. 

** TODO Check if connected to a ZNC instance 
Is it important to check everytime a function runs or sufficient to check once per circe session?
** TODO Generalized *controlpanel interface
IE: zncirce-setchan would prompt for a buffer, then a variable, and based on that, prompt for either a string, integer, or boolean, and send them to *controlpanel.

There is a small problem with this. There are lots of variables at each level, and it probably varies completely across ZNC versions. I could start with a default set, and have a utility function that runs obtaining the help info, saving the values as a tuple (or just the differences).

Something that is likely useful is a reader that does the above, for an arbitrary *module. 

A start would be getting nice looking help buffers. Set a callback, query for help with a module, append the results to a buffer. Looks much better than the circe buffer. Type in a letter to prompt for one of the ones added, possibly, and execute the command. Maybe make them links.
** DONE Fix % bug in circe-actions-message-contents
If you don't want to format the string, (message "%s" VALUE). This avoids any bugs if someone sends a message with % in it.

** wontfix: ZNC's aversion to git
Initially there was going to be some sort of module to access the contents of ZNC's config. This isn't really something that is worth the investment that isn't solved reasonably well by SSHFS (which allows me to use magit).

** TODO Move github presentation to circe-znc
